apiVersion: v1
kind: ConfigMap
metadata:
  name: aspnetfrontendapp
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "EnvironmentConfig": {
        "BackendServiceUrl": "http://dummy.restapiexample.com/api/v1/employees"
      }  
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetfrontendapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetfrontendapp
  template:
    metadata:
      name: aspnetfrontendapp
      labels:
        app: aspnetfrontendapp
        aadpodidbinding: aspnetfrontendapp
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: aspnetfrontendapp
        image: abhinabsarkar/abs-aspnetfrontendapp:v1.0.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        volumeMounts:
        - name: aspnetfrontendapp-volume
          mountPath: /app/config
      volumes:
      - name: aspnetfrontendapp-volume
        configMap:
          name: aspnetfrontendapp                  
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetfrontendapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aspnetfrontendapp